version : '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth
    ports:
      - "8080:8080"
    volumes:
      - "./target/keycloak-experiments-0.1-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-experiments-0.1-SNAPSHOT.jar"
    command: ["start-dev"]