version: '3'

volumes:
  postgres_data:
    driver: local
  caddy_data:
    driver: local

services:
  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
  keycloak:
    image: quay.io/phasetwo/keycloak-crdb:22.0.1
    volumes:
      - ${PWD}/cache-jdbc-persistent.xml:/opt/keycloak/conf/cache-jdbc-persistent.xml
      - ${PWD}/ispn-bundle/target/ispn-bundle-0.1-SNAPSHOT/io.phasetwo-ispn-module-0.1-SNAPSHOT.jar:/opt/keycloak/providers/io.phasetwo-ispn-module-0.1-SNAPSHOT.jar
      - ${PWD}/ispn-bundle/target/ispn-bundle-0.1-SNAPSHOT/org.infinispan-infinispan-cachestore-jdbc-jakarta-14.0.10.Final.jar:/opt/keycloak/providers/org.infinispan-infinispan-cachestore-jdbc-jakarta-14.0.10.Final.jar
      - ${PWD}/ispn-bundle/target/ispn-bundle-0.1-SNAPSHOT/org.infinispan-infinispan-cachestore-jdbc-common-jakarta-14.0.10.Final.jar:/opt/keycloak/providers/org.infinispan-infinispan-cachestore-jdbc-common-jakarta-14.0.10.Final.jar
    environment:
      KC_DB: postgres
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_ISPN_IGNORE_SKIP_CACHE_STORE: 'true'
      KC_ISPN_DB_VENDOR: postgresql
      KC_ISPN_DB_DRIVER: org.postgresql.Driver
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_PROPERTIES: ''
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: 'edge'
      KC_LOG_LEVEL: INFO
      KC_CACHE_CONFIG_FILE: cache-jdbc-persistent.xml
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres
    entrypoint: /opt/keycloak/bin/kc.sh start
  caddy:
    image: caddy:2.4.6-alpine
    restart: unless-stopped
    command: caddy reverse-proxy --from https://localhost:443 --to http://keycloak:8080
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
    depends_on:
      - keycloak
